# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN make install

# 
COPY ./sources /code/sources

# 
CMD ["uvicorn", "sources.main:app", "--host", "0.0.0.0", "--port", "80"]
