# 
FROM python:3.9

# 
WORKDIR /code

# 
COPY ./config/requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# 
COPY ./sources /code/sources

# 
CMD ["uvicorn", "sources.main:app", "--host", "0.0.0.0", "--port", "3000"]
