version: '3'
services:
  jenskins-docker_proyek_pertama:
    image: docker:dind
    container_name: jenskins-docker_proyek_pertama
    privileged: true
    ports:
      - 2376:2376
      - 3000:3000
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    command: --storage-driver=overlay2
    networks:
      jenkins:
        aliases:
          - docker
    volumes:
      - jenkins-docker-certs_proyek_pertama:/certs/client
      - jenkins-data_proyek_pertama:/var/jenkins_home

  jenskins-bluocean_proyek_pertama:
    build:
      context: .
      dockerfile: dockerfile-blueocen
    image: blueocean-proyek-pertama:2.346.1-1
    container_name: jenskins-bluocean_proyek_pertama
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - JAVA_OPTS="-Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true"
    ports:
      - 49000:8080
      - 50000:50000
    volumes:
      - jenkins-docker-certs_proyek_pertama:/certs/client:ro
      - jenkins-data_proyek_pertama:/var/jenkins_home
      - ${HOME}:/home
    # command: sed -i 's/<disableSignup>true<\/disableSignup>/<disableSignup>false<\/disableSignup>/g' /var/jenkins_home/config.xml
    depends_on:
      - jenskins-docker_proyek_pertama

  nginx:
    container_name: my-nginx
    image: nginx
    ports:
      - '9000:9000'
    depends_on:
      - jenskins-docker_proyek_pertama
      - jenskins-bluocean_proyek_pertama
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./access.log:/var/log/nginx/access.log
    networks:
      - jenkins

  prometheus_proyek_pertama:
    image: prom/prometheus:v2.38.0
    container_name: prometheus_proyek_pertama
    ports:
      - 9091:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - jenkins

  grafana_proyek_pertama:
    image: grafana/grafana:9.1.3
    container_name: grafana_proyek_pertama
    environment:
      - GF_SERVER_HTTP_PORT=3031
    ports:
      - 3031:3031
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - jenkins

networks:
  jenkins: {}

volumes:
  jenkins-docker-certs_proyek_pertama: {}
  jenkins-data_proyek_pertama: {}
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
